# Generated by Django 4.1.6 on 2024-06-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('hp', models.CharField(max_length=255)),
            ],
        ),
    ]
